/**
 * This file was generated by the JPA Modeler
 */ 

package entite;

import java.io.Serializable;
import java.sql.Timestamp;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * @author  merguez
 */

@Entity
@XmlRootElement
public class Contrat implements Serializable { 

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    @Basic
    private Double tarif;

    @Basic
    private Boolean actif;

    @Basic
    private java.sql.Timestamp dateCreation;

    @OneToOne(targetEntity = Vehicule.class)
    private Vehicule vehicule;

    @OneToOne(targetEntity = Formule.class)
    private Formule formule;

    @OneToOne(cascade={CascadeType.PERSIST},targetEntity = Utilisation.class)
    private Utilisation utilisation;

    @OneToOne(cascade={CascadeType.PERSIST},targetEntity = Utilisateur.class)
    private Utilisateur utilisateur;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getTarif() {
        return this.tarif;
    }

    public void setTarif(Double tarif) {
        this.tarif = tarif;
    }

    public Boolean isActif() {
        return this.actif;
    }

    public void setActif(Boolean actif) {
        this.actif = actif;
    }

    public Timestamp getDateCreation() {
        return this.dateCreation;
    }

    public void setDateCreation(Timestamp dateCreation) {
        this.dateCreation = dateCreation;
    }

    public Vehicule getVehicule() {
        return this.vehicule;
    }

    public void setVehicule(Vehicule vehicule) {
        this.vehicule = vehicule;
    }

    public Formule getFormule() {
        return this.formule;
    }

    public void setFormule(Formule formule) {
        this.formule = formule;
    }

    public Utilisation getUtilisation() {
        return this.utilisation;
    }

    public void setUtilisation(Utilisation utilisation) {
        this.utilisation = utilisation;
    }

    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }

    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

}
