/**
 * This file was generated by the JPA Modeler
 */ 

package entite;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.Size;import javax.xml.bind.annotation.XmlRootElement;


/**
 * @author  merguez
 */

@Entity@XmlRootElement

public class Utilisateur implements Serializable { 

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    @Column(length=20)
    @Basic
    @Size(min=3,max=20,message="3 caractères min et 20 caractères max")
    private String login;

    @Column(length=40)
    @Basic
    private String password;

    @Basic
    private String email;

    @Column(length=45)
    @Basic
    private String nom;

    @Column(length=45)
    @Basic
    private String prenom;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getPrenom() {
        return this.prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

}
