/**
 * This file was generated by the JPA Modeler
 */ 

package entite;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;import javax.xml.bind.annotation.XmlRootElement;


/**
 * @author  merguez
 */

@Entity@XmlRootElement

public class Utilisation implements Serializable { 

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    @Basic
    private Boolean travail;

    @OneToOne(targetEntity = Kms.class)
    private Kms kms;

    @OneToOne(targetEntity = Frequence.class)
    private Frequence frequence;
    
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean isTravail() {
        return this.travail;
    }

    public void setTravail(Boolean travail) {
        this.travail = travail;
    }

    public Kms getKms() {
        return this.kms;
    }

    public void setKms(Kms kms) {
        this.kms = kms;
    }

    public Frequence getFrequence() {
        return this.frequence;
    }

    public void setFrequence(Frequence frequence) {
        this.frequence = frequence;
    }

}
