/**
 * This file was generated by the JPA Modeler
 */ 

package entite;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;import javax.xml.bind.annotation.XmlRootElement;


/**
 * @author  merguez
 */

@Entity@XmlRootElement

public class Vehicule implements Serializable { 

    @Id
    private Long id;

    @Column(length=45)
    @Basic
    @NotNull
    private String marque;

    @Column(length=45)
    @Basic
    @NotNull
    private String modele;

    @Column(length=45)
    @Basic
    private String version;

    @Basic
    @NotNull
    private Double coefficient;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMarque() {
        return this.marque;
    }

    public void setMarque(String marque) {
        this.marque = marque;
    }

    public String getModele() {
        return this.modele;
    }

    public void setModele(String modele) {
        this.modele = modele;
    }

    public String getVersion() {
        return this.version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public Double getCoefficient() {
        return this.coefficient;
    }

    public void setCoefficient(Double coefficient) {
        this.coefficient = coefficient;
    }

}
